export enum ErrorNamesEnum {
  E_GENERIC_ERROR = "E_GENERIC_ERROR",
  E_UNEXPECTED_ERROR = "E_UNEXPECTED_ERROR",
  E_VALIDATION_ERROR = "E_VALIDATION_ERROR",
  E_NOT_FOUND_ERROR = "E_NOT_FOUND_ERROR",
  E_INTEGRATION_ERROR = "E_INTEGRATION_ERROR",
}
